### ISSUE TITLE
npm start fails

### ISSUE THREAD

**Issue by ankitiitb1069** [evantahler/actionhero-tutorial#28]
I am getting the following error on following the steps for getting started after doing npm start

/home/ankit/actionhero-tutorial/node_modules/actionhero/node_modules/primus/index.js:288
        throw e;
        ^

TypeError: this is not a typed array.
    at Function.from (native)
    at Object.<anonymous> (/home/ankit/actionhero-tutorial/node_modules/actionhero/node_modules/ws/lib/PerMessageDeflate.js:8:24)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ankit/actionhero-tutorial/node_modules/actionhero/node_modules/ws/lib/WebSocket.js:16:27)
    at Module._compile (module.js:409:26)

**Comment by evantahler** [comment]
Dupliate of https://github.com/evantahler/actionhero/issues/1011, we'll handle this in the actionhero repo
